# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: set-env
      uses: allenevans/set-env@v1.1.0
      with:
        # Overwrite existing environment variables
        overwrite: false # optional, default is true
        NODE_ENV: ${{ secrets.NODE_ENV }}
        API_URL: ${{ secrets.API_URL }}
        GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
    - name: Install dependencies and Build
      run: |
        yarn
        npm run build
    - name: Gatsby Publish
      uses: enriikke/gatsby-gh-pages-action@v2.1.1
      with:
        # A personal access token needed to push your site after it has been built.
        access-token: ${{ secrets.ACCESS_TOKEN }}
        # The branch expected by GitHub to have the static files needed for your site.
        deploy-branch: develop # optional, default is master
        # Additional arguments that get passed to `gatsby build`.
        # gatsby-args: # optional, default is 
